### ISSUE TITLE
Tracking list

### ISSUE THREAD

**Issue by gaelik** [gaelik/check_list#1]
Prep Work

 - [x] Request /hab filesystem (size 100GB )
 - [x] Configure the new filesystem
 - [x] Request MS\hab to be unix enabled - Secure does not support < 4 caracters accounts
 - [x] Add hab user and group locally
 - [ ] Configure ES backups (use nas mount shared)
 - [ ] Test that automate-ctl create-backup works
 - [x] Reduce ES size to 2 days
 - [x] ensure that /var/opt/delivery/elasticsearch only contains the /data directory

Outage Starts

 - [ ] Disable automate forwarding on Front Ends - comment out all lines starting by automate in .rb
 - [ ] Disable profile failure during automate downtime updating major environments

default['audit']['raise_if_unreachable'] = false

 - [ ] upgrade ES to 6.2.2
 - [ ] Ensure that ES 6.2.2 includes repo.path and correct host binding info
 - [ ] Run a manual automate backup 

 automate-ctl create-backup 

 - [ ] Clear rabbitMQ queue manually if needed: 

PATH=/opt/delivery/embedded/bin:$PATH rabbitmqctl purge_queue data-collector -p /insights PATH=/opt/delivery/embedded/bin:$PATH rabbitmqctl list_queues -p /insights

 - [ ] Follow https://automate.chef.io/docs/upgrade/ process to download chef-automate binary
 - [ ] Run preflight and abort when  asked

chef-automate upgrade-from-v1 --channel current --skip-external-es-check 

 - [ ] Edit preflight generated file adding Elastic Search info including memory lock and heap 16G, add the following entries to the  config-20180919xxxxx.toml file created by the previous process.

[elasticsearch]
  [elasticsearch.v1]
    [elasticsearch.v1.sys]
      [elasticsearch.v1.sys.cluster]
        name = "chef-stg"
      [elasticsearch.v1.sys.node]
        master = false
      [elasticsearch.v1.sys.network]
        host = "0.0.0.0"
      [elasticsearch.v1.sys.transport]
        port = "9300-9400"
      [elasticsearch.v1.sys.discovery]
        ping_unicast_hosts = "[x,x,x,x,x]"
      [elasticsearch.v1.sys.runtime]
        heapsize = "16g"
        max_open_files = "65536"
        max_locked_memory = "unlimited"

 - [ ] Run upgrade with -c config file parameter generated above.

chef-automate upgrade-from-v1 --channel current --skip-external-es-check --skip-preflight -c config-20180919xxxxx.toml 

- [ ] Check status

chef-automate status

- [ ] Check Errors 

journalctl -u chef-automate -n 10000

- [ ] Reenable Front End - uncomment automate lines and run a reconfigure

**Comment by jeremymv2** [comment]
Nice @gaelik some questions I have:

- Are you going to prune any historical indices via the reaper ahead of time? This is not necessary, but just wanted to mention it since it came up earlier. Perhaps you have mentioned only keeping 24 hours? Again, not necessary, just wanted to bring it up.
- `ensure that /var/opt/delivery/elasticsearch only contains the /data directory` really should mean the `data` directory ends up empty. 😄
